### ISSUE TITLE
UPDATED ABOUT/TIMLINE

### ISSUE THREAD

**Issue by schelna** [CSC496-MobileProject/VillaKatherine#18]
Villa Kathrine 
ABOUT
A Mediterranean castle on the Mississippi bluffs, this structure was built in 1900 for world traveler George Metz and is open for tours. It boasts an interior courtyard with reflecting pool and is now home to Quincy’s Tourist Info Center, as well as the Quincy Area Convention and Visitors Bureau.

TIMELINE
1897 George Metz tours North Africa and Spain for two years, gathering materials and inspiration for the building of a Moorish “villa” of his own, using the Villa Ben Ahben in Morocco as a starting point.
1899 Metz returns to Quincy, collects his notes and sketches, and confers with several architects about creating a composite design.
1900 An ideal spot for Metz’s villa is located on the bluff south of State Street.  Young Quincy architect George Behersmeyer draws up the plans, reducing the Moroccan villa to 43’ by 53’ specifying walls of brick with pure white plaster veneer.  Construction of the Villa Kathrine begins with Herman Schactseick as the prime contractor.
1901 Villa Kathrine is completed, its main tower decorated with latticework inspired by Giralda in Seville, Spain, and topped with a minaret replicating in miniature that on the Mosque of Thais in Tunisia.  A sky-lit interior court is surrounded by columns who arrangement recalls the Court of Dolls in the Alcazar in Seville and whose twisted form and capitals are inspired by the famed Alhambra in Granada.
1904 The “Moorish dream palace” is described and illustrated in the March issue of Scientific American Builders Weekly.
1912 Metz sells Villa Kathrine to Quincy grocer Archibald Behrens, who turns out to be acting for the Quincy and Western Illinois Railway. The QWIR proposes to build a line to Alton using the Metz property for a railroad yard.  Behrens and his wife, an accomplished artist, ar promised the contents of the house as sales commission, but end up with only a rug.  Local entrepreneur John J. Fisher, a principal backer of the railroad, becomes virtual owner of the property and is believed by Metz to have furnished his home with the Islamic collection. 
1917 The interurban rail project fails, and ownership of the former Metz property enters 18 years of litigation. Meanwhile the house becomes derelict and is rented out at low rates.
1928 Behrens gives up all claim to the property for $1, and the house begins more than a decade of abandonment.
1933 Metz returns to the Villa with a reporter. When asked why he named it the Villa Kathrine, he only chuckled and did not answer.
1937 Metz dies in Quincy at the age of 88.
1939 Under the ownership of Fisher’s company, Excelsior Stove Works, the house undergoes its first restoration.  Central heating is installed, the reflecting pool is filled with concrete, and the grounds are plastered with lombardy poplars.
1941 The Chicago Daily News publish a feature on the still-empty “Moroccan villa” on the Mississippi.
1942 Musician and nightclub owner Bob Moore rents the house with his wife Christine and two children, who are students at Quincy College. (Now known as Quincy University)
1951 Harold C. McCoy purchases the house, repairs the casement windows and dome, modernizes the electricity, and landscapes the grounds with flowering shrubs and catalpas.
1954 Porter Settle, Jr., buys the house for development into a supper club that soon abandons the project.
1955 Quincy Park District purchases the Villa Kathrine and several lots to the north with a $25,000 donation from the Moorman Company, demolishes the remaining housing, and turns the enlarged property into a neighborhood park and community center under the supervision of the Franklin Neighborhood committee.
1966 The grounds of Villa Katherine are further enlarged through purchase of a residential lot on Third Street.
1976 The Park district partially restores and upgrades the Villa and various citizen groups engage in two years of debate concerning the feasibility of restoration and reuse.
1977 The Park District estimates the cost of complete restoration at $150,000, the figure rising to $200,000 the following year.
1978 The Quincy Jaycettes, led by Sharron Jett, nominate Villa Kathrine to the National Register of Historic Places, spearhead a clean-up effort, and form “Friends of the Castle” as a support group for the Villa Kathrine restoration and reuse.
1779 Quincy Park District leases the Villa Kathrine to Friends of the Castle, and architect Carl Fisher and Associates of Springfield develops a phased restoration proposal.  
1981 The City of Quincy, the Federal Highway Administration, Illinois Department of Transportation and Quincy Park District jointly develop a program for the Villa Kathrine as a tourist center.
1984 The Great River Road Commission provides a $225,000 grant for Phase 1 of work at the Villa Kathrine, with a $75,000 match to be raised locally.
1986 Waterkotte Construction completes Phase 1, including restoration of the exterior and front parlor, construction of public restrooms, and a driveway and parking lot.
1987 Bergman Nurseries replants the grounds using many shrubs of near Eastern origin.
1993 The Illinois Department of Transportation grants $300,000 for finishing exterior restoration, reworking mechanical and electrical systems, and returning the interior to its original plan and appearance.  A local match of $75,000 is required. Friends of the Castle retains Poepping, Stone, Bach and Associates as architects and engineers of the restoration, with Robert Christie as consultant.
1998 Friends of the Castle completes restoration of the Villa Kathrine.

**Comment by schelna** [comment]
George Metz, Eccentric or Visionary?
William George Mets was born in Quincy on May 20, 1849. His parents, William and Anna Katherine Kientzle Metz, emigrated from Germany with their families, met in Iowa, then moved to Quincy in 1847. After beginning in the furniture business, William Metz entered the drug business that was to lay the basis for a great family fortune. He started out as a pharmacist with Ferdinand Flachs, then operated independently, and finally joined Flachs’ successor, Aldo Sommer, as a partner.
William’s death in 1873 left a widow and two grown children, with William George (familiarly known as George) the sole male heir. On May 6, 1897 George’s mother dies, impelling him on a prolonged tour of the Mediterranean Europe and Africa. He returned to Quincy in 1899 and immediately set about planning a hilltop residence that would capture the spirit and atmosphere – as well as some of the actual detail – of late medieval Islamic buildings.
Construction began to George Behrenmeyer’s plans in 1900 and was completed the following year. The residence was dubbed “Villa Kathrine” after Metz’s mother, though legend has also attached that name to a lost love. Metz’s only constant companion there was his beloved dog, Bingo. Brought over from Demark by Metz himself, Bingo was a 212-pound Great Dane reputed to be the largest dog in America. But, metz was not a total recluse. Warm summer nights often found him dining with friends on the roof of the northwest tower. On September 30, 1904 Albert Hastings and Pansy Darnell, an old family friend of Metz’s, were married at the Villa, with George Metz playing the Wedding March on his pipe organ.
When Bingo died in 1906, a cloud descended over Metz’s oriental dream. Out of fear for his safety, George’s relatives implored him to move, and a visiting couple, professing great enthusiasm for the artistry of the dwelling and its furnishings, prevailed on him to sell. In 1912 Metz gave in and walked away from the house and its contents, even though he knew by the time that the buyer was an agent for an interurban railway company planning to use the property for a railroad yard. 
Metz briefly visited the Villa with a St. Louis newspaper reporter the following year to find the house overrun with vermin and birds, its tinted wall designs marred and its costly furnishings either stripped or in shreds. He left it vowing he “never never will return to look upon this ruin.” Nineteen years later, Metz reneged on his vow, returning this time with a Decatur reporter to see the exterior overtaken by decay. “I wish the place were mine again,” he said. “I’d tear it down.”

**Comment by ghost** [comment]
All text has been updated
